'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace WSRV
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="WSRV.ServiceSoap")>  _
    Public Interface ServiceSoap
        
        'CODEGEN: Se está generando un contrato de mensaje, ya que el mensaje GetTicketRequest tiene encabezados.
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GetTicket", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function GetTicket(ByVal request As WSRV.GetTicketRequest) As WSRV.GetTicketResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GetTicket", ReplyAction:="*")>  _
        Function GetTicketAsync(ByVal request As WSRV.GetTicketRequest) As System.Threading.Tasks.Task(Of WSRV.GetTicketResponse)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GetTicketSC", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function GetTicketSC(ByVal strUserName As String, ByVal strPassword As String, ByVal base64Cfd As String) As WSRV.StructCfd
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GetTicketSC", ReplyAction:="*")>  _
        Function GetTicketSCAsync(ByVal strUserName As String, ByVal strPassword As String, ByVal base64Cfd As String) As System.Threading.Tasks.Task(Of WSRV.StructCfd)
        
        'CODEGEN: Se está generando un contrato de mensaje, ya que el mensaje GetTicketCSFRequest tiene encabezados.
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GetTicketCSF", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function GetTicketCSF(ByVal request As WSRV.GetTicketCSFRequest) As WSRV.GetTicketCSFResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GetTicketCSF", ReplyAction:="*")>  _
        Function GetTicketCSFAsync(ByVal request As WSRV.GetTicketCSFRequest) As System.Threading.Tasks.Task(Of WSRV.GetTicketCSFResponse)
        
        'CODEGEN: Se está generando un contrato de mensaje, ya que el mensaje GetTicketAURequest tiene encabezados.
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GetTicketAU", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function GetTicketAU(ByVal request As WSRV.GetTicketAURequest) As WSRV.GetTicketAUResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GetTicketAU", ReplyAction:="*")>  _
        Function GetTicketAUAsync(ByVal request As WSRV.GetTicketAURequest) As System.Threading.Tasks.Task(Of WSRV.GetTicketAUResponse)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/TimbrarCDClave", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function TimbrarCDClave(ByVal rfc_emisor As String, ByVal usuario_ws As String, ByVal clave_ws As String, ByVal base64Cfd As String, ByVal cadena_xml As String, ByVal ClaveServicio As String) As WSRV.StructCfd
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/TimbrarCDClave", ReplyAction:="*")>  _
        Function TimbrarCDClaveAsync(ByVal rfc_emisor As String, ByVal usuario_ws As String, ByVal clave_ws As String, ByVal base64Cfd As String, ByVal cadena_xml As String, ByVal ClaveServicio As String) As System.Threading.Tasks.Task(Of WSRV.StructCfd)
        
        'CODEGEN: Se está generando un contrato de mensaje, ya que el mensaje TestCfd33Request tiene encabezados.
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/TestCfd33", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function TestCfd33(ByVal request As WSRV.TestCfd33Request) As WSRV.TestCfd33Response
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/TestCfd33", ReplyAction:="*")>  _
        Function TestCfd33Async(ByVal request As WSRV.TestCfd33Request) As System.Threading.Tasks.Task(Of WSRV.TestCfd33Response)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/TestCfd33SC", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function TestCfd33SC(ByVal strUserName As String, ByVal strPassword As String, ByVal base64Cfd As String) As WSRV.StructCfd
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/TestCfd33SC", ReplyAction:="*")>  _
        Function TestCfd33SCAsync(ByVal strUserName As String, ByVal strPassword As String, ByVal base64Cfd As String) As System.Threading.Tasks.Task(Of WSRV.StructCfd)
        
        'CODEGEN: Se está generando un contrato de mensaje, ya que el mensaje CancelTicketRequest tiene encabezados.
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/CancelTicket", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function CancelTicket(ByVal request As WSRV.CancelTicketRequest) As WSRV.CancelTicketResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/CancelTicket", ReplyAction:="*")>  _
        Function CancelTicketAsync(ByVal request As WSRV.CancelTicketRequest) As System.Threading.Tasks.Task(Of WSRV.CancelTicketResponse)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/CancelTicketSC", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function CancelTicketSC(ByVal strUserName As String, ByVal strPassword As String, ByVal base64Cfd As String) As WSRV.StructCancel
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/CancelTicketSC", ReplyAction:="*")>  _
        Function CancelTicketSCAsync(ByVal strUserName As String, ByVal strPassword As String, ByVal base64Cfd As String) As System.Threading.Tasks.Task(Of WSRV.StructCancel)
        
        'CODEGEN: Se está generando un contrato de mensaje, ya que el mensaje CancelTicketExtRequest tiene encabezados.
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/CancelTicketExt", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function CancelTicketExt(ByVal request As WSRV.CancelTicketExtRequest) As WSRV.CancelTicketExtResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/CancelTicketExt", ReplyAction:="*")>  _
        Function CancelTicketExtAsync(ByVal request As WSRV.CancelTicketExtRequest) As System.Threading.Tasks.Task(Of WSRV.CancelTicketExtResponse)
        
        'CODEGEN: Se está generando un contrato de mensaje, ya que el mensaje CancelTestRequest tiene encabezados.
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/CancelTest", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function CancelTest(ByVal request As WSRV.CancelTestRequest) As WSRV.CancelTestResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/CancelTest", ReplyAction:="*")>  _
        Function CancelTestAsync(ByVal request As WSRV.CancelTestRequest) As System.Threading.Tasks.Task(Of WSRV.CancelTestResponse)
        
        'CODEGEN: Se está generando un contrato de mensaje, ya que el mensaje ConsultarSolicitudesPendientesDeCancelacionRequest tiene encabezados.
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ConsultarSolicitudesPendientesDeCancelacion", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function ConsultarSolicitudesPendientesDeCancelacion(ByVal request As WSRV.ConsultarSolicitudesPendientesDeCancelacionRequest) As WSRV.ConsultarSolicitudesPendientesDeCancelacionResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ConsultarSolicitudesPendientesDeCancelacion", ReplyAction:="*")>  _
        Function ConsultarSolicitudesPendientesDeCancelacionAsync(ByVal request As WSRV.ConsultarSolicitudesPendientesDeCancelacionRequest) As System.Threading.Tasks.Task(Of WSRV.ConsultarSolicitudesPendientesDeCancelacionResponse)
        
        'CODEGEN: Se está generando un contrato de mensaje, ya que el mensaje AceptarRechazarSolicitudDeCancelacionRequest tiene encabezados.
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/AceptarRechazarSolicitudDeCancelacion", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function AceptarRechazarSolicitudDeCancelacion(ByVal request As WSRV.AceptarRechazarSolicitudDeCancelacionRequest) As WSRV.AceptarRechazarSolicitudDeCancelacionResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/AceptarRechazarSolicitudDeCancelacion", ReplyAction:="*")>  _
        Function AceptarRechazarSolicitudDeCancelacionAsync(ByVal request As WSRV.AceptarRechazarSolicitudDeCancelacionRequest) As System.Threading.Tasks.Task(Of WSRV.AceptarRechazarSolicitudDeCancelacionResponse)
        
        'CODEGEN: Se está generando un contrato de mensaje, ya que el mensaje EstatusCFDIRequest tiene encabezados.
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/EstatusCFDI", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function EstatusCFDI(ByVal request As WSRV.EstatusCFDIRequest) As WSRV.EstatusCFDIResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/EstatusCFDI", ReplyAction:="*")>  _
        Function EstatusCFDIAsync(ByVal request As WSRV.EstatusCFDIRequest) As System.Threading.Tasks.Task(Of WSRV.EstatusCFDIResponse)
        
        'CODEGEN: Se está generando un contrato de mensaje, ya que el mensaje GenerarPdf33Request tiene encabezados.
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GenerarPdf33", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function GenerarPdf33(ByVal request As WSRV.GenerarPdf33Request) As WSRV.GenerarPdf33Response
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GenerarPdf33", ReplyAction:="*")>  _
        Function GenerarPdf33Async(ByVal request As WSRV.GenerarPdf33Request) As System.Threading.Tasks.Task(Of WSRV.GenerarPdf33Response)
        
        'CODEGEN: Se está generando un contrato de mensaje, ya que el mensaje GenerarPdf33InternoRequest tiene encabezados.
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GenerarPdf33Interno", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function GenerarPdf33Interno(ByVal request As WSRV.GenerarPdf33InternoRequest) As WSRV.GenerarPdf33InternoResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GenerarPdf33Interno", ReplyAction:="*")>  _
        Function GenerarPdf33InternoAsync(ByVal request As WSRV.GenerarPdf33InternoRequest) As System.Threading.Tasks.Task(Of WSRV.GenerarPdf33InternoResponse)
    End Interface
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class AuthSoapHd
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private strUserNameField As String
        
        Private strPasswordField As String
        
        Private anyAttrField() As System.Xml.XmlAttribute
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property strUserName() As String
            Get
                Return Me.strUserNameField
            End Get
            Set
                Me.strUserNameField = value
                Me.RaisePropertyChanged("strUserName")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=1)>  _
        Public Property strPassword() As String
            Get
                Return Me.strPasswordField
            End Get
            Set
                Me.strPasswordField = value
                Me.RaisePropertyChanged("strPassword")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAnyAttributeAttribute()>  _
        Public Property AnyAttr() As System.Xml.XmlAttribute()
            Get
                Return Me.anyAttrField
            End Get
            Set
                Me.anyAttrField = value
                Me.RaisePropertyChanged("AnyAttr")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class StructPDF
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private archivoField() As Byte
        
        Private descripcionField As String
        
        Private estadoField As Integer
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary", Order:=0)>  _
        Public Property Archivo() As Byte()
            Get
                Return Me.archivoField
            End Get
            Set
                Me.archivoField = value
                Me.RaisePropertyChanged("Archivo")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=1)>  _
        Public Property Descripcion() As String
            Get
                Return Me.descripcionField
            End Get
            Set
                Me.descripcionField = value
                Me.RaisePropertyChanged("Descripcion")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=2)>  _
        Public Property Estado() As Integer
            Get
                Return Me.estadoField
            End Get
            Set
                Me.estadoField = value
                Me.RaisePropertyChanged("Estado")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class invoicesStatus
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private uuidField As System.Guid
        
        Private estatusUUIDField As String
        
        Private respuestaField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property uuid() As System.Guid
            Get
                Return Me.uuidField
            End Get
            Set
                Me.uuidField = value
                Me.RaisePropertyChanged("uuid")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=1)>  _
        Public Property estatusUUID() As String
            Get
                Return Me.estatusUUIDField
            End Get
            Set
                Me.estatusUUIDField = value
                Me.RaisePropertyChanged("estatusUUID")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=2)>  _
        Public Property respuesta() As String
            Get
                Return Me.respuestaField
            End Get
            Set
                Me.respuestaField = value
                Me.RaisePropertyChanged("respuesta")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class StructAceptarRechazar
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private estatusField As String
        
        Private codigoEstatusField As String
        
        Private acuseField As String
        
        Private foliosField() As invoicesStatus
        
        Private mensajeField As String
        
        Private descripcionField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property Estatus() As String
            Get
                Return Me.estatusField
            End Get
            Set
                Me.estatusField = value
                Me.RaisePropertyChanged("Estatus")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=1)>  _
        Public Property CodigoEstatus() As String
            Get
                Return Me.codigoEstatusField
            End Get
            Set
                Me.codigoEstatusField = value
                Me.RaisePropertyChanged("CodigoEstatus")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=2)>  _
        Public Property Acuse() As String
            Get
                Return Me.acuseField
            End Get
            Set
                Me.acuseField = value
                Me.RaisePropertyChanged("Acuse")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayAttribute(Order:=3)>  _
        Public Property Folios() As invoicesStatus()
            Get
                Return Me.foliosField
            End Get
            Set
                Me.foliosField = value
                Me.RaisePropertyChanged("Folios")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=4)>  _
        Public Property Mensaje() As String
            Get
                Return Me.mensajeField
            End Get
            Set
                Me.mensajeField = value
                Me.RaisePropertyChanged("Mensaje")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=5)>  _
        Public Property Descripcion() As String
            Get
                Return Me.descripcionField
            End Get
            Set
                Me.descripcionField = value
                Me.RaisePropertyChanged("Descripcion")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class StructSolicitudesPendientes
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private estatusField As String
        
        Private codigoEstatusField As String
        
        Private uUIDsField() As String
        
        Private mensajeField As String
        
        Private descripcionField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property Estatus() As String
            Get
                Return Me.estatusField
            End Get
            Set
                Me.estatusField = value
                Me.RaisePropertyChanged("Estatus")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=1)>  _
        Public Property CodigoEstatus() As String
            Get
                Return Me.codigoEstatusField
            End Get
            Set
                Me.codigoEstatusField = value
                Me.RaisePropertyChanged("CodigoEstatus")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayAttribute(Order:=2)>  _
        Public Property UUIDs() As String()
            Get
                Return Me.uUIDsField
            End Get
            Set
                Me.uUIDsField = value
                Me.RaisePropertyChanged("UUIDs")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=3)>  _
        Public Property Mensaje() As String
            Get
                Return Me.mensajeField
            End Get
            Set
                Me.mensajeField = value
                Me.RaisePropertyChanged("Mensaje")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=4)>  _
        Public Property Descripcion() As String
            Get
                Return Me.descripcionField
            End Get
            Set
                Me.descripcionField = value
                Me.RaisePropertyChanged("Descripcion")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class StructCancel
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private estatusCFDIField As String
        
        Private rfcSolicitanteField As String
        
        Private fechaField As String
        
        Private uUIDsField As String
        
        Private noSerieFirmanteField As String
        
        Private descripcionField As String
        
        Private stateField As Integer
        
        Private acuseField As String
        
        Private rutaDescargaAcuseField As String
        
        Private esCancelableField As String
        
        Private estatusCancelacionField As String
        
        Private mensajeField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property EstatusCFDI() As String
            Get
                Return Me.estatusCFDIField
            End Get
            Set
                Me.estatusCFDIField = value
                Me.RaisePropertyChanged("EstatusCFDI")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=1)>  _
        Public Property RfcSolicitante() As String
            Get
                Return Me.rfcSolicitanteField
            End Get
            Set
                Me.rfcSolicitanteField = value
                Me.RaisePropertyChanged("RfcSolicitante")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=2)>  _
        Public Property Fecha() As String
            Get
                Return Me.fechaField
            End Get
            Set
                Me.fechaField = value
                Me.RaisePropertyChanged("Fecha")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=3)>  _
        Public Property UUIDs() As String
            Get
                Return Me.uUIDsField
            End Get
            Set
                Me.uUIDsField = value
                Me.RaisePropertyChanged("UUIDs")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=4)>  _
        Public Property NoSerieFirmante() As String
            Get
                Return Me.noSerieFirmanteField
            End Get
            Set
                Me.noSerieFirmanteField = value
                Me.RaisePropertyChanged("NoSerieFirmante")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=5)>  _
        Public Property Descripcion() As String
            Get
                Return Me.descripcionField
            End Get
            Set
                Me.descripcionField = value
                Me.RaisePropertyChanged("Descripcion")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=6)>  _
        Public Property state() As Integer
            Get
                Return Me.stateField
            End Get
            Set
                Me.stateField = value
                Me.RaisePropertyChanged("state")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=7)>  _
        Public Property Acuse() As String
            Get
                Return Me.acuseField
            End Get
            Set
                Me.acuseField = value
                Me.RaisePropertyChanged("Acuse")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=8)>  _
        Public Property RutaDescargaAcuse() As String
            Get
                Return Me.rutaDescargaAcuseField
            End Get
            Set
                Me.rutaDescargaAcuseField = value
                Me.RaisePropertyChanged("RutaDescargaAcuse")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=9)>  _
        Public Property EsCancelable() As String
            Get
                Return Me.esCancelableField
            End Get
            Set
                Me.esCancelableField = value
                Me.RaisePropertyChanged("EsCancelable")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=10)>  _
        Public Property EstatusCancelacion() As String
            Get
                Return Me.estatusCancelacionField
            End Get
            Set
                Me.estatusCancelacionField = value
                Me.RaisePropertyChanged("EstatusCancelacion")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=11)>  _
        Public Property Mensaje() As String
            Get
                Return Me.mensajeField
            End Get
            Set
                Me.mensajeField = value
                Me.RaisePropertyChanged("Mensaje")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class StructCfd
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private rfcEmisorField As String
        
        Private rfcReceptorField As String
        
        Private versionField As String
        
        Private serieField As String
        
        Private folioField As String
        
        Private fechaExpedicionField As String
        
        Private montoOperacionField As String
        
        Private montoImpuestoField As String
        
        Private tipoComprobanteField As String
        
        Private cadenaField As String
        
        Private firmaField As String
        
        Private serieCertificadoField As String
        
        Private cfdiField As String
        
        Private timbreField As String
        
        Private descripcionField As String
        
        Private stateField As Integer
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property RfcEmisor() As String
            Get
                Return Me.rfcEmisorField
            End Get
            Set
                Me.rfcEmisorField = value
                Me.RaisePropertyChanged("RfcEmisor")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=1)>  _
        Public Property RfcReceptor() As String
            Get
                Return Me.rfcReceptorField
            End Get
            Set
                Me.rfcReceptorField = value
                Me.RaisePropertyChanged("RfcReceptor")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=2)>  _
        Public Property Version() As String
            Get
                Return Me.versionField
            End Get
            Set
                Me.versionField = value
                Me.RaisePropertyChanged("Version")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=3)>  _
        Public Property Serie() As String
            Get
                Return Me.serieField
            End Get
            Set
                Me.serieField = value
                Me.RaisePropertyChanged("Serie")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=4)>  _
        Public Property Folio() As String
            Get
                Return Me.folioField
            End Get
            Set
                Me.folioField = value
                Me.RaisePropertyChanged("Folio")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=5)>  _
        Public Property FechaExpedicion() As String
            Get
                Return Me.fechaExpedicionField
            End Get
            Set
                Me.fechaExpedicionField = value
                Me.RaisePropertyChanged("FechaExpedicion")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=6)>  _
        Public Property MontoOperacion() As String
            Get
                Return Me.montoOperacionField
            End Get
            Set
                Me.montoOperacionField = value
                Me.RaisePropertyChanged("MontoOperacion")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=7)>  _
        Public Property MontoImpuesto() As String
            Get
                Return Me.montoImpuestoField
            End Get
            Set
                Me.montoImpuestoField = value
                Me.RaisePropertyChanged("MontoImpuesto")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=8)>  _
        Public Property TipoComprobante() As String
            Get
                Return Me.tipoComprobanteField
            End Get
            Set
                Me.tipoComprobanteField = value
                Me.RaisePropertyChanged("TipoComprobante")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=9)>  _
        Public Property Cadena() As String
            Get
                Return Me.cadenaField
            End Get
            Set
                Me.cadenaField = value
                Me.RaisePropertyChanged("Cadena")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=10)>  _
        Public Property Firma() As String
            Get
                Return Me.firmaField
            End Get
            Set
                Me.firmaField = value
                Me.RaisePropertyChanged("Firma")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=11)>  _
        Public Property SerieCertificado() As String
            Get
                Return Me.serieCertificadoField
            End Get
            Set
                Me.serieCertificadoField = value
                Me.RaisePropertyChanged("SerieCertificado")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=12)>  _
        Public Property Cfdi() As String
            Get
                Return Me.cfdiField
            End Get
            Set
                Me.cfdiField = value
                Me.RaisePropertyChanged("Cfdi")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=13)>  _
        Public Property Timbre() As String
            Get
                Return Me.timbreField
            End Get
            Set
                Me.timbreField = value
                Me.RaisePropertyChanged("Timbre")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=14)>  _
        Public Property Descripcion() As String
            Get
                Return Me.descripcionField
            End Get
            Set
                Me.descripcionField = value
                Me.RaisePropertyChanged("Descripcion")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=15)>  _
        Public Property state() As Integer
            Get
                Return Me.stateField
            End Get
            Set
                Me.stateField = value
                Me.RaisePropertyChanged("state")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="GetTicket", WrapperNamespace:="http://tempuri.org/", IsWrapped:=true)>  _
    Partial Public Class GetTicketRequest
        
        <System.ServiceModel.MessageHeaderAttribute([Namespace]:="http://tempuri.org/")>  _
        Public AuthSoapHd As WSRV.AuthSoapHd
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public base64Cfd As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal AuthSoapHd As WSRV.AuthSoapHd, ByVal base64Cfd As String)
            MyBase.New
            Me.AuthSoapHd = AuthSoapHd
            Me.base64Cfd = base64Cfd
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="GetTicketResponse", WrapperNamespace:="http://tempuri.org/", IsWrapped:=true)>  _
    Partial Public Class GetTicketResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public GetTicketResult As WSRV.StructCfd
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal GetTicketResult As WSRV.StructCfd)
            MyBase.New
            Me.GetTicketResult = GetTicketResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="GetTicketCSF", WrapperNamespace:="http://tempuri.org/", IsWrapped:=true)>  _
    Partial Public Class GetTicketCSFRequest
        
        <System.ServiceModel.MessageHeaderAttribute([Namespace]:="http://tempuri.org/")>  _
        Public AuthSoapHd As WSRV.AuthSoapHd
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public base64Cfd As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal AuthSoapHd As WSRV.AuthSoapHd, ByVal base64Cfd As String)
            MyBase.New
            Me.AuthSoapHd = AuthSoapHd
            Me.base64Cfd = base64Cfd
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="GetTicketCSFResponse", WrapperNamespace:="http://tempuri.org/", IsWrapped:=true)>  _
    Partial Public Class GetTicketCSFResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public GetTicketCSFResult As WSRV.StructCfd
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal GetTicketCSFResult As WSRV.StructCfd)
            MyBase.New
            Me.GetTicketCSFResult = GetTicketCSFResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="GetTicketAU", WrapperNamespace:="http://tempuri.org/", IsWrapped:=true)>  _
    Partial Public Class GetTicketAURequest
        
        <System.ServiceModel.MessageHeaderAttribute([Namespace]:="http://tempuri.org/")>  _
        Public AuthSoapHd As WSRV.AuthSoapHd
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public base64Cfd As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=1)>  _
        Public rfcAdministrador As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=2)>  _
        Public cuentaAdministrador As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=3)>  _
        Public claveAdministrador As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal AuthSoapHd As WSRV.AuthSoapHd, ByVal base64Cfd As String, ByVal rfcAdministrador As String, ByVal cuentaAdministrador As String, ByVal claveAdministrador As String)
            MyBase.New
            Me.AuthSoapHd = AuthSoapHd
            Me.base64Cfd = base64Cfd
            Me.rfcAdministrador = rfcAdministrador
            Me.cuentaAdministrador = cuentaAdministrador
            Me.claveAdministrador = claveAdministrador
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="GetTicketAUResponse", WrapperNamespace:="http://tempuri.org/", IsWrapped:=true)>  _
    Partial Public Class GetTicketAUResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public GetTicketAUResult As WSRV.StructCfd
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal GetTicketAUResult As WSRV.StructCfd)
            MyBase.New
            Me.GetTicketAUResult = GetTicketAUResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="TestCfd33", WrapperNamespace:="http://tempuri.org/", IsWrapped:=true)>  _
    Partial Public Class TestCfd33Request
        
        <System.ServiceModel.MessageHeaderAttribute([Namespace]:="http://tempuri.org/")>  _
        Public AuthSoapHd As WSRV.AuthSoapHd
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public base64Cfd As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal AuthSoapHd As WSRV.AuthSoapHd, ByVal base64Cfd As String)
            MyBase.New
            Me.AuthSoapHd = AuthSoapHd
            Me.base64Cfd = base64Cfd
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="TestCfd33Response", WrapperNamespace:="http://tempuri.org/", IsWrapped:=true)>  _
    Partial Public Class TestCfd33Response
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public TestCfd33Result As WSRV.StructCfd
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal TestCfd33Result As WSRV.StructCfd)
            MyBase.New
            Me.TestCfd33Result = TestCfd33Result
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="CancelTicket", WrapperNamespace:="http://tempuri.org/", IsWrapped:=true)>  _
    Partial Public Class CancelTicketRequest
        
        <System.ServiceModel.MessageHeaderAttribute([Namespace]:="http://tempuri.org/")>  _
        Public AuthSoapHd As WSRV.AuthSoapHd
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public base64Cfd As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal AuthSoapHd As WSRV.AuthSoapHd, ByVal base64Cfd As String)
            MyBase.New
            Me.AuthSoapHd = AuthSoapHd
            Me.base64Cfd = base64Cfd
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="CancelTicketResponse", WrapperNamespace:="http://tempuri.org/", IsWrapped:=true)>  _
    Partial Public Class CancelTicketResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public CancelTicketResult As WSRV.StructCancel
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal CancelTicketResult As WSRV.StructCancel)
            MyBase.New
            Me.CancelTicketResult = CancelTicketResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="CancelTicketExt", WrapperNamespace:="http://tempuri.org/", IsWrapped:=true)>  _
    Partial Public Class CancelTicketExtRequest
        
        <System.ServiceModel.MessageHeaderAttribute([Namespace]:="http://tempuri.org/")>  _
        Public AuthSoapHd As WSRV.AuthSoapHd
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public base64Cfd As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=1)>  _
        Public totalfactura As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=2)>  _
        Public rfcreceptor As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal AuthSoapHd As WSRV.AuthSoapHd, ByVal base64Cfd As String, ByVal totalfactura As String, ByVal rfcreceptor As String)
            MyBase.New
            Me.AuthSoapHd = AuthSoapHd
            Me.base64Cfd = base64Cfd
            Me.totalfactura = totalfactura
            Me.rfcreceptor = rfcreceptor
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="CancelTicketExtResponse", WrapperNamespace:="http://tempuri.org/", IsWrapped:=true)>  _
    Partial Public Class CancelTicketExtResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public CancelTicketExtResult As WSRV.StructCancel
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal CancelTicketExtResult As WSRV.StructCancel)
            MyBase.New
            Me.CancelTicketExtResult = CancelTicketExtResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="CancelTest", WrapperNamespace:="http://tempuri.org/", IsWrapped:=true)>  _
    Partial Public Class CancelTestRequest
        
        <System.ServiceModel.MessageHeaderAttribute([Namespace]:="http://tempuri.org/")>  _
        Public AuthSoapHd As WSRV.AuthSoapHd
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public CanB64 As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal AuthSoapHd As WSRV.AuthSoapHd, ByVal CanB64 As String)
            MyBase.New
            Me.AuthSoapHd = AuthSoapHd
            Me.CanB64 = CanB64
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="CancelTestResponse", WrapperNamespace:="http://tempuri.org/", IsWrapped:=true)>  _
    Partial Public Class CancelTestResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public CancelTestResult As WSRV.StructCancel
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal CancelTestResult As WSRV.StructCancel)
            MyBase.New
            Me.CancelTestResult = CancelTestResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="ConsultarSolicitudesPendientesDeCancelacion", WrapperNamespace:="http://tempuri.org/", IsWrapped:=true)>  _
    Partial Public Class ConsultarSolicitudesPendientesDeCancelacionRequest
        
        <System.ServiceModel.MessageHeaderAttribute([Namespace]:="http://tempuri.org/")>  _
        Public AuthSoapHd As WSRV.AuthSoapHd
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public RfcReceptor As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=1)>  _
        Public produccion As Boolean
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal AuthSoapHd As WSRV.AuthSoapHd, ByVal RfcReceptor As String, ByVal produccion As Boolean)
            MyBase.New
            Me.AuthSoapHd = AuthSoapHd
            Me.RfcReceptor = RfcReceptor
            Me.produccion = produccion
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="ConsultarSolicitudesPendientesDeCancelacionResponse", WrapperNamespace:="http://tempuri.org/", IsWrapped:=true)>  _
    Partial Public Class ConsultarSolicitudesPendientesDeCancelacionResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public ConsultarSolicitudesPendientesDeCancelacionResult As WSRV.StructSolicitudesPendientes
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal ConsultarSolicitudesPendientesDeCancelacionResult As WSRV.StructSolicitudesPendientes)
            MyBase.New
            Me.ConsultarSolicitudesPendientesDeCancelacionResult = ConsultarSolicitudesPendientesDeCancelacionResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="AceptarRechazarSolicitudDeCancelacion", WrapperNamespace:="http://tempuri.org/", IsWrapped:=true)>  _
    Partial Public Class AceptarRechazarSolicitudDeCancelacionRequest
        
        <System.ServiceModel.MessageHeaderAttribute([Namespace]:="http://tempuri.org/")>  _
        Public AuthSoapHd As WSRV.AuthSoapHd
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public xml As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=1)>  _
        Public produccion As Boolean
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=2)>  _
        Public aceptacion As Boolean
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal AuthSoapHd As WSRV.AuthSoapHd, ByVal xml As String, ByVal produccion As Boolean, ByVal aceptacion As Boolean)
            MyBase.New
            Me.AuthSoapHd = AuthSoapHd
            Me.xml = xml
            Me.produccion = produccion
            Me.aceptacion = aceptacion
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="AceptarRechazarSolicitudDeCancelacionResponse", WrapperNamespace:="http://tempuri.org/", IsWrapped:=true)>  _
    Partial Public Class AceptarRechazarSolicitudDeCancelacionResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public AceptarRechazarSolicitudDeCancelacionResult As WSRV.StructAceptarRechazar
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal AceptarRechazarSolicitudDeCancelacionResult As WSRV.StructAceptarRechazar)
            MyBase.New
            Me.AceptarRechazarSolicitudDeCancelacionResult = AceptarRechazarSolicitudDeCancelacionResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="EstatusCFDI", WrapperNamespace:="http://tempuri.org/", IsWrapped:=true)>  _
    Partial Public Class EstatusCFDIRequest
        
        <System.ServiceModel.MessageHeaderAttribute([Namespace]:="http://tempuri.org/")>  _
        Public AuthSoapHd As WSRV.AuthSoapHd
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public RfcEmisor As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=1)>  _
        Public RfcReceptor As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=2)>  _
        Public total As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=3)>  _
        Public uuid As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal AuthSoapHd As WSRV.AuthSoapHd, ByVal RfcEmisor As String, ByVal RfcReceptor As String, ByVal total As String, ByVal uuid As String)
            MyBase.New
            Me.AuthSoapHd = AuthSoapHd
            Me.RfcEmisor = RfcEmisor
            Me.RfcReceptor = RfcReceptor
            Me.total = total
            Me.uuid = uuid
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="EstatusCFDIResponse", WrapperNamespace:="http://tempuri.org/", IsWrapped:=true)>  _
    Partial Public Class EstatusCFDIResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public EstatusCFDIResult As WSRV.StructCancel
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal EstatusCFDIResult As WSRV.StructCancel)
            MyBase.New
            Me.EstatusCFDIResult = EstatusCFDIResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="GenerarPdf33", WrapperNamespace:="http://tempuri.org/", IsWrapped:=true)>  _
    Partial Public Class GenerarPdf33Request
        
        <System.ServiceModel.MessageHeaderAttribute([Namespace]:="http://tempuri.org/")>  _
        Public AuthSoapHd As WSRV.AuthSoapHd
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public XMLBase64 As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=1)>  _
        Public EstatusCFDI As Boolean
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=2)>  _
        Public TipoCFDI As Integer
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=3),  _
         System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary")>  _
        Public Logo() As Byte
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=4)>  _
        Public Telefono As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=5)>  _
        Public Correo As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=6)>  _
        Public Observacion As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal AuthSoapHd As WSRV.AuthSoapHd, ByVal XMLBase64 As String, ByVal EstatusCFDI As Boolean, ByVal TipoCFDI As Integer, ByVal Logo() As Byte, ByVal Telefono As String, ByVal Correo As String, ByVal Observacion As String)
            MyBase.New
            Me.AuthSoapHd = AuthSoapHd
            Me.XMLBase64 = XMLBase64
            Me.EstatusCFDI = EstatusCFDI
            Me.TipoCFDI = TipoCFDI
            Me.Logo = Logo
            Me.Telefono = Telefono
            Me.Correo = Correo
            Me.Observacion = Observacion
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="GenerarPdf33Response", WrapperNamespace:="http://tempuri.org/", IsWrapped:=true)>  _
    Partial Public Class GenerarPdf33Response
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public GenerarPdf33Result As WSRV.StructPDF
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal GenerarPdf33Result As WSRV.StructPDF)
            MyBase.New
            Me.GenerarPdf33Result = GenerarPdf33Result
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="GenerarPdf33Interno", WrapperNamespace:="http://tempuri.org/", IsWrapped:=true)>  _
    Partial Public Class GenerarPdf33InternoRequest
        
        <System.ServiceModel.MessageHeaderAttribute([Namespace]:="http://tempuri.org/")>  _
        Public AuthSoapHd As WSRV.AuthSoapHd
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public XMLBase64 As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=1)>  _
        Public EstatusCFDI As Boolean
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=2)>  _
        Public TipoCFDI As Integer
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=3),  _
         System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary")>  _
        Public Logo() As Byte
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=4)>  _
        Public Telefono As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=5)>  _
        Public Correo As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=6)>  _
        Public Observacion As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=7)>  _
        Public uid As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=8)>  _
        Public claveAccesoServicio As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal AuthSoapHd As WSRV.AuthSoapHd, ByVal XMLBase64 As String, ByVal EstatusCFDI As Boolean, ByVal TipoCFDI As Integer, ByVal Logo() As Byte, ByVal Telefono As String, ByVal Correo As String, ByVal Observacion As String, ByVal uid As String, ByVal claveAccesoServicio As String)
            MyBase.New
            Me.AuthSoapHd = AuthSoapHd
            Me.XMLBase64 = XMLBase64
            Me.EstatusCFDI = EstatusCFDI
            Me.TipoCFDI = TipoCFDI
            Me.Logo = Logo
            Me.Telefono = Telefono
            Me.Correo = Correo
            Me.Observacion = Observacion
            Me.uid = uid
            Me.claveAccesoServicio = claveAccesoServicio
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="GenerarPdf33InternoResponse", WrapperNamespace:="http://tempuri.org/", IsWrapped:=true)>  _
    Partial Public Class GenerarPdf33InternoResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public GenerarPdf33InternoResult As WSRV.StructPDF
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal GenerarPdf33InternoResult As WSRV.StructPDF)
            MyBase.New
            Me.GenerarPdf33InternoResult = GenerarPdf33InternoResult
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface ServiceSoapChannel
        Inherits WSRV.ServiceSoap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class ServiceSoapClient
        Inherits System.ServiceModel.ClientBase(Of WSRV.ServiceSoap)
        Implements WSRV.ServiceSoap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WSRV_ServiceSoap_GetTicket(ByVal request As WSRV.GetTicketRequest) As WSRV.GetTicketResponse Implements WSRV.ServiceSoap.GetTicket
            Return MyBase.Channel.GetTicket(request)
        End Function
        
        Public Function GetTicket(ByVal AuthSoapHd As WSRV.AuthSoapHd, ByVal base64Cfd As String) As WSRV.StructCfd
            Dim inValue As WSRV.GetTicketRequest = New WSRV.GetTicketRequest()
            inValue.AuthSoapHd = AuthSoapHd
            inValue.base64Cfd = base64Cfd
            Dim retVal As WSRV.GetTicketResponse = CType(Me,WSRV.ServiceSoap).GetTicket(inValue)
            Return retVal.GetTicketResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WSRV_ServiceSoap_GetTicketAsync(ByVal request As WSRV.GetTicketRequest) As System.Threading.Tasks.Task(Of WSRV.GetTicketResponse) Implements WSRV.ServiceSoap.GetTicketAsync
            Return MyBase.Channel.GetTicketAsync(request)
        End Function
        
        Public Function GetTicketAsync(ByVal AuthSoapHd As WSRV.AuthSoapHd, ByVal base64Cfd As String) As System.Threading.Tasks.Task(Of WSRV.GetTicketResponse)
            Dim inValue As WSRV.GetTicketRequest = New WSRV.GetTicketRequest()
            inValue.AuthSoapHd = AuthSoapHd
            inValue.base64Cfd = base64Cfd
            Return CType(Me,WSRV.ServiceSoap).GetTicketAsync(inValue)
        End Function
        
        Public Function GetTicketSC(ByVal strUserName As String, ByVal strPassword As String, ByVal base64Cfd As String) As WSRV.StructCfd Implements WSRV.ServiceSoap.GetTicketSC
            Return MyBase.Channel.GetTicketSC(strUserName, strPassword, base64Cfd)
        End Function
        
        Public Function GetTicketSCAsync(ByVal strUserName As String, ByVal strPassword As String, ByVal base64Cfd As String) As System.Threading.Tasks.Task(Of WSRV.StructCfd) Implements WSRV.ServiceSoap.GetTicketSCAsync
            Return MyBase.Channel.GetTicketSCAsync(strUserName, strPassword, base64Cfd)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WSRV_ServiceSoap_GetTicketCSF(ByVal request As WSRV.GetTicketCSFRequest) As WSRV.GetTicketCSFResponse Implements WSRV.ServiceSoap.GetTicketCSF
            Return MyBase.Channel.GetTicketCSF(request)
        End Function
        
        Public Function GetTicketCSF(ByVal AuthSoapHd As WSRV.AuthSoapHd, ByVal base64Cfd As String) As WSRV.StructCfd
            Dim inValue As WSRV.GetTicketCSFRequest = New WSRV.GetTicketCSFRequest()
            inValue.AuthSoapHd = AuthSoapHd
            inValue.base64Cfd = base64Cfd
            Dim retVal As WSRV.GetTicketCSFResponse = CType(Me,WSRV.ServiceSoap).GetTicketCSF(inValue)
            Return retVal.GetTicketCSFResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WSRV_ServiceSoap_GetTicketCSFAsync(ByVal request As WSRV.GetTicketCSFRequest) As System.Threading.Tasks.Task(Of WSRV.GetTicketCSFResponse) Implements WSRV.ServiceSoap.GetTicketCSFAsync
            Return MyBase.Channel.GetTicketCSFAsync(request)
        End Function
        
        Public Function GetTicketCSFAsync(ByVal AuthSoapHd As WSRV.AuthSoapHd, ByVal base64Cfd As String) As System.Threading.Tasks.Task(Of WSRV.GetTicketCSFResponse)
            Dim inValue As WSRV.GetTicketCSFRequest = New WSRV.GetTicketCSFRequest()
            inValue.AuthSoapHd = AuthSoapHd
            inValue.base64Cfd = base64Cfd
            Return CType(Me,WSRV.ServiceSoap).GetTicketCSFAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WSRV_ServiceSoap_GetTicketAU(ByVal request As WSRV.GetTicketAURequest) As WSRV.GetTicketAUResponse Implements WSRV.ServiceSoap.GetTicketAU
            Return MyBase.Channel.GetTicketAU(request)
        End Function
        
        Public Function GetTicketAU(ByVal AuthSoapHd As WSRV.AuthSoapHd, ByVal base64Cfd As String, ByVal rfcAdministrador As String, ByVal cuentaAdministrador As String, ByVal claveAdministrador As String) As WSRV.StructCfd
            Dim inValue As WSRV.GetTicketAURequest = New WSRV.GetTicketAURequest()
            inValue.AuthSoapHd = AuthSoapHd
            inValue.base64Cfd = base64Cfd
            inValue.rfcAdministrador = rfcAdministrador
            inValue.cuentaAdministrador = cuentaAdministrador
            inValue.claveAdministrador = claveAdministrador
            Dim retVal As WSRV.GetTicketAUResponse = CType(Me,WSRV.ServiceSoap).GetTicketAU(inValue)
            Return retVal.GetTicketAUResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WSRV_ServiceSoap_GetTicketAUAsync(ByVal request As WSRV.GetTicketAURequest) As System.Threading.Tasks.Task(Of WSRV.GetTicketAUResponse) Implements WSRV.ServiceSoap.GetTicketAUAsync
            Return MyBase.Channel.GetTicketAUAsync(request)
        End Function
        
        Public Function GetTicketAUAsync(ByVal AuthSoapHd As WSRV.AuthSoapHd, ByVal base64Cfd As String, ByVal rfcAdministrador As String, ByVal cuentaAdministrador As String, ByVal claveAdministrador As String) As System.Threading.Tasks.Task(Of WSRV.GetTicketAUResponse)
            Dim inValue As WSRV.GetTicketAURequest = New WSRV.GetTicketAURequest()
            inValue.AuthSoapHd = AuthSoapHd
            inValue.base64Cfd = base64Cfd
            inValue.rfcAdministrador = rfcAdministrador
            inValue.cuentaAdministrador = cuentaAdministrador
            inValue.claveAdministrador = claveAdministrador
            Return CType(Me,WSRV.ServiceSoap).GetTicketAUAsync(inValue)
        End Function
        
        Public Function TimbrarCDClave(ByVal rfc_emisor As String, ByVal usuario_ws As String, ByVal clave_ws As String, ByVal base64Cfd As String, ByVal cadena_xml As String, ByVal ClaveServicio As String) As WSRV.StructCfd Implements WSRV.ServiceSoap.TimbrarCDClave
            Return MyBase.Channel.TimbrarCDClave(rfc_emisor, usuario_ws, clave_ws, base64Cfd, cadena_xml, ClaveServicio)
        End Function
        
        Public Function TimbrarCDClaveAsync(ByVal rfc_emisor As String, ByVal usuario_ws As String, ByVal clave_ws As String, ByVal base64Cfd As String, ByVal cadena_xml As String, ByVal ClaveServicio As String) As System.Threading.Tasks.Task(Of WSRV.StructCfd) Implements WSRV.ServiceSoap.TimbrarCDClaveAsync
            Return MyBase.Channel.TimbrarCDClaveAsync(rfc_emisor, usuario_ws, clave_ws, base64Cfd, cadena_xml, ClaveServicio)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WSRV_ServiceSoap_TestCfd33(ByVal request As WSRV.TestCfd33Request) As WSRV.TestCfd33Response Implements WSRV.ServiceSoap.TestCfd33
            Return MyBase.Channel.TestCfd33(request)
        End Function
        
        Public Function TestCfd33(ByVal AuthSoapHd As WSRV.AuthSoapHd, ByVal base64Cfd As String) As WSRV.StructCfd
            Dim inValue As WSRV.TestCfd33Request = New WSRV.TestCfd33Request()
            inValue.AuthSoapHd = AuthSoapHd
            inValue.base64Cfd = base64Cfd
            Dim retVal As WSRV.TestCfd33Response = CType(Me,WSRV.ServiceSoap).TestCfd33(inValue)
            Return retVal.TestCfd33Result
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WSRV_ServiceSoap_TestCfd33Async(ByVal request As WSRV.TestCfd33Request) As System.Threading.Tasks.Task(Of WSRV.TestCfd33Response) Implements WSRV.ServiceSoap.TestCfd33Async
            Return MyBase.Channel.TestCfd33Async(request)
        End Function
        
        Public Function TestCfd33Async(ByVal AuthSoapHd As WSRV.AuthSoapHd, ByVal base64Cfd As String) As System.Threading.Tasks.Task(Of WSRV.TestCfd33Response)
            Dim inValue As WSRV.TestCfd33Request = New WSRV.TestCfd33Request()
            inValue.AuthSoapHd = AuthSoapHd
            inValue.base64Cfd = base64Cfd
            Return CType(Me,WSRV.ServiceSoap).TestCfd33Async(inValue)
        End Function
        
        Public Function TestCfd33SC(ByVal strUserName As String, ByVal strPassword As String, ByVal base64Cfd As String) As WSRV.StructCfd Implements WSRV.ServiceSoap.TestCfd33SC
            Return MyBase.Channel.TestCfd33SC(strUserName, strPassword, base64Cfd)
        End Function
        
        Public Function TestCfd33SCAsync(ByVal strUserName As String, ByVal strPassword As String, ByVal base64Cfd As String) As System.Threading.Tasks.Task(Of WSRV.StructCfd) Implements WSRV.ServiceSoap.TestCfd33SCAsync
            Return MyBase.Channel.TestCfd33SCAsync(strUserName, strPassword, base64Cfd)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WSRV_ServiceSoap_CancelTicket(ByVal request As WSRV.CancelTicketRequest) As WSRV.CancelTicketResponse Implements WSRV.ServiceSoap.CancelTicket
            Return MyBase.Channel.CancelTicket(request)
        End Function
        
        Public Function CancelTicket(ByVal AuthSoapHd As WSRV.AuthSoapHd, ByVal base64Cfd As String) As WSRV.StructCancel
            Dim inValue As WSRV.CancelTicketRequest = New WSRV.CancelTicketRequest()
            inValue.AuthSoapHd = AuthSoapHd
            inValue.base64Cfd = base64Cfd
            Dim retVal As WSRV.CancelTicketResponse = CType(Me,WSRV.ServiceSoap).CancelTicket(inValue)
            Return retVal.CancelTicketResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WSRV_ServiceSoap_CancelTicketAsync(ByVal request As WSRV.CancelTicketRequest) As System.Threading.Tasks.Task(Of WSRV.CancelTicketResponse) Implements WSRV.ServiceSoap.CancelTicketAsync
            Return MyBase.Channel.CancelTicketAsync(request)
        End Function
        
        Public Function CancelTicketAsync(ByVal AuthSoapHd As WSRV.AuthSoapHd, ByVal base64Cfd As String) As System.Threading.Tasks.Task(Of WSRV.CancelTicketResponse)
            Dim inValue As WSRV.CancelTicketRequest = New WSRV.CancelTicketRequest()
            inValue.AuthSoapHd = AuthSoapHd
            inValue.base64Cfd = base64Cfd
            Return CType(Me,WSRV.ServiceSoap).CancelTicketAsync(inValue)
        End Function
        
        Public Function CancelTicketSC(ByVal strUserName As String, ByVal strPassword As String, ByVal base64Cfd As String) As WSRV.StructCancel Implements WSRV.ServiceSoap.CancelTicketSC
            Return MyBase.Channel.CancelTicketSC(strUserName, strPassword, base64Cfd)
        End Function
        
        Public Function CancelTicketSCAsync(ByVal strUserName As String, ByVal strPassword As String, ByVal base64Cfd As String) As System.Threading.Tasks.Task(Of WSRV.StructCancel) Implements WSRV.ServiceSoap.CancelTicketSCAsync
            Return MyBase.Channel.CancelTicketSCAsync(strUserName, strPassword, base64Cfd)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WSRV_ServiceSoap_CancelTicketExt(ByVal request As WSRV.CancelTicketExtRequest) As WSRV.CancelTicketExtResponse Implements WSRV.ServiceSoap.CancelTicketExt
            Return MyBase.Channel.CancelTicketExt(request)
        End Function
        
        Public Function CancelTicketExt(ByVal AuthSoapHd As WSRV.AuthSoapHd, ByVal base64Cfd As String, ByVal totalfactura As String, ByVal rfcreceptor As String) As WSRV.StructCancel
            Dim inValue As WSRV.CancelTicketExtRequest = New WSRV.CancelTicketExtRequest()
            inValue.AuthSoapHd = AuthSoapHd
            inValue.base64Cfd = base64Cfd
            inValue.totalfactura = totalfactura
            inValue.rfcreceptor = rfcreceptor
            Dim retVal As WSRV.CancelTicketExtResponse = CType(Me,WSRV.ServiceSoap).CancelTicketExt(inValue)
            Return retVal.CancelTicketExtResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WSRV_ServiceSoap_CancelTicketExtAsync(ByVal request As WSRV.CancelTicketExtRequest) As System.Threading.Tasks.Task(Of WSRV.CancelTicketExtResponse) Implements WSRV.ServiceSoap.CancelTicketExtAsync
            Return MyBase.Channel.CancelTicketExtAsync(request)
        End Function
        
        Public Function CancelTicketExtAsync(ByVal AuthSoapHd As WSRV.AuthSoapHd, ByVal base64Cfd As String, ByVal totalfactura As String, ByVal rfcreceptor As String) As System.Threading.Tasks.Task(Of WSRV.CancelTicketExtResponse)
            Dim inValue As WSRV.CancelTicketExtRequest = New WSRV.CancelTicketExtRequest()
            inValue.AuthSoapHd = AuthSoapHd
            inValue.base64Cfd = base64Cfd
            inValue.totalfactura = totalfactura
            inValue.rfcreceptor = rfcreceptor
            Return CType(Me,WSRV.ServiceSoap).CancelTicketExtAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WSRV_ServiceSoap_CancelTest(ByVal request As WSRV.CancelTestRequest) As WSRV.CancelTestResponse Implements WSRV.ServiceSoap.CancelTest
            Return MyBase.Channel.CancelTest(request)
        End Function
        
        Public Function CancelTest(ByVal AuthSoapHd As WSRV.AuthSoapHd, ByVal CanB64 As String) As WSRV.StructCancel
            Dim inValue As WSRV.CancelTestRequest = New WSRV.CancelTestRequest()
            inValue.AuthSoapHd = AuthSoapHd
            inValue.CanB64 = CanB64
            Dim retVal As WSRV.CancelTestResponse = CType(Me,WSRV.ServiceSoap).CancelTest(inValue)
            Return retVal.CancelTestResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WSRV_ServiceSoap_CancelTestAsync(ByVal request As WSRV.CancelTestRequest) As System.Threading.Tasks.Task(Of WSRV.CancelTestResponse) Implements WSRV.ServiceSoap.CancelTestAsync
            Return MyBase.Channel.CancelTestAsync(request)
        End Function
        
        Public Function CancelTestAsync(ByVal AuthSoapHd As WSRV.AuthSoapHd, ByVal CanB64 As String) As System.Threading.Tasks.Task(Of WSRV.CancelTestResponse)
            Dim inValue As WSRV.CancelTestRequest = New WSRV.CancelTestRequest()
            inValue.AuthSoapHd = AuthSoapHd
            inValue.CanB64 = CanB64
            Return CType(Me,WSRV.ServiceSoap).CancelTestAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WSRV_ServiceSoap_ConsultarSolicitudesPendientesDeCancelacion(ByVal request As WSRV.ConsultarSolicitudesPendientesDeCancelacionRequest) As WSRV.ConsultarSolicitudesPendientesDeCancelacionResponse Implements WSRV.ServiceSoap.ConsultarSolicitudesPendientesDeCancelacion
            Return MyBase.Channel.ConsultarSolicitudesPendientesDeCancelacion(request)
        End Function
        
        Public Function ConsultarSolicitudesPendientesDeCancelacion(ByVal AuthSoapHd As WSRV.AuthSoapHd, ByVal RfcReceptor As String, ByVal produccion As Boolean) As WSRV.StructSolicitudesPendientes
            Dim inValue As WSRV.ConsultarSolicitudesPendientesDeCancelacionRequest = New WSRV.ConsultarSolicitudesPendientesDeCancelacionRequest()
            inValue.AuthSoapHd = AuthSoapHd
            inValue.RfcReceptor = RfcReceptor
            inValue.produccion = produccion
            Dim retVal As WSRV.ConsultarSolicitudesPendientesDeCancelacionResponse = CType(Me,WSRV.ServiceSoap).ConsultarSolicitudesPendientesDeCancelacion(inValue)
            Return retVal.ConsultarSolicitudesPendientesDeCancelacionResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WSRV_ServiceSoap_ConsultarSolicitudesPendientesDeCancelacionAsync(ByVal request As WSRV.ConsultarSolicitudesPendientesDeCancelacionRequest) As System.Threading.Tasks.Task(Of WSRV.ConsultarSolicitudesPendientesDeCancelacionResponse) Implements WSRV.ServiceSoap.ConsultarSolicitudesPendientesDeCancelacionAsync
            Return MyBase.Channel.ConsultarSolicitudesPendientesDeCancelacionAsync(request)
        End Function
        
        Public Function ConsultarSolicitudesPendientesDeCancelacionAsync(ByVal AuthSoapHd As WSRV.AuthSoapHd, ByVal RfcReceptor As String, ByVal produccion As Boolean) As System.Threading.Tasks.Task(Of WSRV.ConsultarSolicitudesPendientesDeCancelacionResponse)
            Dim inValue As WSRV.ConsultarSolicitudesPendientesDeCancelacionRequest = New WSRV.ConsultarSolicitudesPendientesDeCancelacionRequest()
            inValue.AuthSoapHd = AuthSoapHd
            inValue.RfcReceptor = RfcReceptor
            inValue.produccion = produccion
            Return CType(Me,WSRV.ServiceSoap).ConsultarSolicitudesPendientesDeCancelacionAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WSRV_ServiceSoap_AceptarRechazarSolicitudDeCancelacion(ByVal request As WSRV.AceptarRechazarSolicitudDeCancelacionRequest) As WSRV.AceptarRechazarSolicitudDeCancelacionResponse Implements WSRV.ServiceSoap.AceptarRechazarSolicitudDeCancelacion
            Return MyBase.Channel.AceptarRechazarSolicitudDeCancelacion(request)
        End Function
        
        Public Function AceptarRechazarSolicitudDeCancelacion(ByVal AuthSoapHd As WSRV.AuthSoapHd, ByVal xml As String, ByVal produccion As Boolean, ByVal aceptacion As Boolean) As WSRV.StructAceptarRechazar
            Dim inValue As WSRV.AceptarRechazarSolicitudDeCancelacionRequest = New WSRV.AceptarRechazarSolicitudDeCancelacionRequest()
            inValue.AuthSoapHd = AuthSoapHd
            inValue.xml = xml
            inValue.produccion = produccion
            inValue.aceptacion = aceptacion
            Dim retVal As WSRV.AceptarRechazarSolicitudDeCancelacionResponse = CType(Me,WSRV.ServiceSoap).AceptarRechazarSolicitudDeCancelacion(inValue)
            Return retVal.AceptarRechazarSolicitudDeCancelacionResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WSRV_ServiceSoap_AceptarRechazarSolicitudDeCancelacionAsync(ByVal request As WSRV.AceptarRechazarSolicitudDeCancelacionRequest) As System.Threading.Tasks.Task(Of WSRV.AceptarRechazarSolicitudDeCancelacionResponse) Implements WSRV.ServiceSoap.AceptarRechazarSolicitudDeCancelacionAsync
            Return MyBase.Channel.AceptarRechazarSolicitudDeCancelacionAsync(request)
        End Function
        
        Public Function AceptarRechazarSolicitudDeCancelacionAsync(ByVal AuthSoapHd As WSRV.AuthSoapHd, ByVal xml As String, ByVal produccion As Boolean, ByVal aceptacion As Boolean) As System.Threading.Tasks.Task(Of WSRV.AceptarRechazarSolicitudDeCancelacionResponse)
            Dim inValue As WSRV.AceptarRechazarSolicitudDeCancelacionRequest = New WSRV.AceptarRechazarSolicitudDeCancelacionRequest()
            inValue.AuthSoapHd = AuthSoapHd
            inValue.xml = xml
            inValue.produccion = produccion
            inValue.aceptacion = aceptacion
            Return CType(Me,WSRV.ServiceSoap).AceptarRechazarSolicitudDeCancelacionAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WSRV_ServiceSoap_EstatusCFDI(ByVal request As WSRV.EstatusCFDIRequest) As WSRV.EstatusCFDIResponse Implements WSRV.ServiceSoap.EstatusCFDI
            Return MyBase.Channel.EstatusCFDI(request)
        End Function
        
        Public Function EstatusCFDI(ByVal AuthSoapHd As WSRV.AuthSoapHd, ByVal RfcEmisor As String, ByVal RfcReceptor As String, ByVal total As String, ByVal uuid As String) As WSRV.StructCancel
            Dim inValue As WSRV.EstatusCFDIRequest = New WSRV.EstatusCFDIRequest()
            inValue.AuthSoapHd = AuthSoapHd
            inValue.RfcEmisor = RfcEmisor
            inValue.RfcReceptor = RfcReceptor
            inValue.total = total
            inValue.uuid = uuid
            Dim retVal As WSRV.EstatusCFDIResponse = CType(Me,WSRV.ServiceSoap).EstatusCFDI(inValue)
            Return retVal.EstatusCFDIResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WSRV_ServiceSoap_EstatusCFDIAsync(ByVal request As WSRV.EstatusCFDIRequest) As System.Threading.Tasks.Task(Of WSRV.EstatusCFDIResponse) Implements WSRV.ServiceSoap.EstatusCFDIAsync
            Return MyBase.Channel.EstatusCFDIAsync(request)
        End Function
        
        Public Function EstatusCFDIAsync(ByVal AuthSoapHd As WSRV.AuthSoapHd, ByVal RfcEmisor As String, ByVal RfcReceptor As String, ByVal total As String, ByVal uuid As String) As System.Threading.Tasks.Task(Of WSRV.EstatusCFDIResponse)
            Dim inValue As WSRV.EstatusCFDIRequest = New WSRV.EstatusCFDIRequest()
            inValue.AuthSoapHd = AuthSoapHd
            inValue.RfcEmisor = RfcEmisor
            inValue.RfcReceptor = RfcReceptor
            inValue.total = total
            inValue.uuid = uuid
            Return CType(Me,WSRV.ServiceSoap).EstatusCFDIAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WSRV_ServiceSoap_GenerarPdf33(ByVal request As WSRV.GenerarPdf33Request) As WSRV.GenerarPdf33Response Implements WSRV.ServiceSoap.GenerarPdf33
            Return MyBase.Channel.GenerarPdf33(request)
        End Function
        
        Public Function GenerarPdf33(ByVal AuthSoapHd As WSRV.AuthSoapHd, ByVal XMLBase64 As String, ByVal EstatusCFDI As Boolean, ByVal TipoCFDI As Integer, ByVal Logo() As Byte, ByVal Telefono As String, ByVal Correo As String, ByVal Observacion As String) As WSRV.StructPDF
            Dim inValue As WSRV.GenerarPdf33Request = New WSRV.GenerarPdf33Request()
            inValue.AuthSoapHd = AuthSoapHd
            inValue.XMLBase64 = XMLBase64
            inValue.EstatusCFDI = EstatusCFDI
            inValue.TipoCFDI = TipoCFDI
            inValue.Logo = Logo
            inValue.Telefono = Telefono
            inValue.Correo = Correo
            inValue.Observacion = Observacion
            Dim retVal As WSRV.GenerarPdf33Response = CType(Me,WSRV.ServiceSoap).GenerarPdf33(inValue)
            Return retVal.GenerarPdf33Result
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WSRV_ServiceSoap_GenerarPdf33Async(ByVal request As WSRV.GenerarPdf33Request) As System.Threading.Tasks.Task(Of WSRV.GenerarPdf33Response) Implements WSRV.ServiceSoap.GenerarPdf33Async
            Return MyBase.Channel.GenerarPdf33Async(request)
        End Function
        
        Public Function GenerarPdf33Async(ByVal AuthSoapHd As WSRV.AuthSoapHd, ByVal XMLBase64 As String, ByVal EstatusCFDI As Boolean, ByVal TipoCFDI As Integer, ByVal Logo() As Byte, ByVal Telefono As String, ByVal Correo As String, ByVal Observacion As String) As System.Threading.Tasks.Task(Of WSRV.GenerarPdf33Response)
            Dim inValue As WSRV.GenerarPdf33Request = New WSRV.GenerarPdf33Request()
            inValue.AuthSoapHd = AuthSoapHd
            inValue.XMLBase64 = XMLBase64
            inValue.EstatusCFDI = EstatusCFDI
            inValue.TipoCFDI = TipoCFDI
            inValue.Logo = Logo
            inValue.Telefono = Telefono
            inValue.Correo = Correo
            inValue.Observacion = Observacion
            Return CType(Me,WSRV.ServiceSoap).GenerarPdf33Async(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WSRV_ServiceSoap_GenerarPdf33Interno(ByVal request As WSRV.GenerarPdf33InternoRequest) As WSRV.GenerarPdf33InternoResponse Implements WSRV.ServiceSoap.GenerarPdf33Interno
            Return MyBase.Channel.GenerarPdf33Interno(request)
        End Function
        
        Public Function GenerarPdf33Interno(ByVal AuthSoapHd As WSRV.AuthSoapHd, ByVal XMLBase64 As String, ByVal EstatusCFDI As Boolean, ByVal TipoCFDI As Integer, ByVal Logo() As Byte, ByVal Telefono As String, ByVal Correo As String, ByVal Observacion As String, ByVal uid As String, ByVal claveAccesoServicio As String) As WSRV.StructPDF
            Dim inValue As WSRV.GenerarPdf33InternoRequest = New WSRV.GenerarPdf33InternoRequest()
            inValue.AuthSoapHd = AuthSoapHd
            inValue.XMLBase64 = XMLBase64
            inValue.EstatusCFDI = EstatusCFDI
            inValue.TipoCFDI = TipoCFDI
            inValue.Logo = Logo
            inValue.Telefono = Telefono
            inValue.Correo = Correo
            inValue.Observacion = Observacion
            inValue.uid = uid
            inValue.claveAccesoServicio = claveAccesoServicio
            Dim retVal As WSRV.GenerarPdf33InternoResponse = CType(Me,WSRV.ServiceSoap).GenerarPdf33Interno(inValue)
            Return retVal.GenerarPdf33InternoResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WSRV_ServiceSoap_GenerarPdf33InternoAsync(ByVal request As WSRV.GenerarPdf33InternoRequest) As System.Threading.Tasks.Task(Of WSRV.GenerarPdf33InternoResponse) Implements WSRV.ServiceSoap.GenerarPdf33InternoAsync
            Return MyBase.Channel.GenerarPdf33InternoAsync(request)
        End Function
        
        Public Function GenerarPdf33InternoAsync(ByVal AuthSoapHd As WSRV.AuthSoapHd, ByVal XMLBase64 As String, ByVal EstatusCFDI As Boolean, ByVal TipoCFDI As Integer, ByVal Logo() As Byte, ByVal Telefono As String, ByVal Correo As String, ByVal Observacion As String, ByVal uid As String, ByVal claveAccesoServicio As String) As System.Threading.Tasks.Task(Of WSRV.GenerarPdf33InternoResponse)
            Dim inValue As WSRV.GenerarPdf33InternoRequest = New WSRV.GenerarPdf33InternoRequest()
            inValue.AuthSoapHd = AuthSoapHd
            inValue.XMLBase64 = XMLBase64
            inValue.EstatusCFDI = EstatusCFDI
            inValue.TipoCFDI = TipoCFDI
            inValue.Logo = Logo
            inValue.Telefono = Telefono
            inValue.Correo = Correo
            inValue.Observacion = Observacion
            inValue.uid = uid
            inValue.claveAccesoServicio = claveAccesoServicio
            Return CType(Me,WSRV.ServiceSoap).GenerarPdf33InternoAsync(inValue)
        End Function
    End Class
End Namespace
